### ISSUE TITLE
bar图横置(x-y轴交换)

### ISSUE THREAD

**Issue by pudgetutu** [pyecharts/pyecharts#684] opened 2018-08-17 09:40 UTC
**问题**
官方效果
![1](https://user-images.githubusercontent.com/17973396/44259479-29f1fa00-a244-11e8-8f08-42c7b4349c40.png)
实际效果
![2](https://user-images.githubusercontent.com/17973396/44259481-2a8a9080-a244-11e8-8bec-a46747acb382.png)
如图，用的样例代码，交换后y轴没有正常显示文字

**运行环境（系统环境及 pyecharts 版本）**
win7,
pyecharts                          0.5.8
pyecharts-javascripthon            0.0.6
pyecharts-jupyter-installer        0.0.3
pyecharts-snapshot                 0.1.7

**代码及截图**
    attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    v1 = [5, 20, 36, 10, 75, 90]
    v2 = [10, 25, 8, 60, 20, 80]
    bar = Bar("x 轴和 y 轴交换")
    bar.add("商家A", attr, v1)
    bar.add("商家B", attr, v2, is_convert=True)
    bar.render()

**Comment by chfw** [comment] 2018-08-17 09:56
duplicate of #653

**Closed by chfw** 2018-08-17 09:56 UTC
